foreground = "#bfbdb6"
background = "#0b0e14"
cursor = "#e6b450"
selection_bg = "#409fff"
selection_fg = "#0b0e14"
black = "#11151c"
red = "#ea6c73"
green = "#7fd962"
yellow = "#f9af4f"
blue = "#53bdfa"
magenta = "#cda1fa"
cyan = "#90e1c6"
white = "#c7c7c7"
bright_black = "#7a7a7a"
bright_red = "#f07178"
bright_green = "#aad94c"
bright_yellow = "#ffb454"
bright_blue = "#59c2ff"
bright_magenta = "#d2a6ff"
bright_cyan = "#95e6cb"
bright_white = "#ffffff"
