foreground = "#ffffff"
background = "#132738"
cursor = "#f0cc09"
selection_bg = "#18354f"
selection_fg = "#b5b5b5"
black = "#000000"
red = "#ff0000"
green = "#38de21"
yellow = "#ffe50a"
blue = "#6cb5ff"
magenta = "#ff005d"
cyan = "#00bbbb"
white = "#bbbbbb"
bright_black = "#8a959e"
bright_red = "#f40e17"
bright_green = "#3bd01d"
bright_yellow = "#edc809"
bright_blue = "#6a6aff"
bright_magenta = "#ff55ff"
bright_cyan = "#6ae3fa"
bright_white = "#ffffff"
