# source: https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/windowsterminal/GitHub%20Dark%20Default.json
foreground = "#e6edf3"
background = "#0d1117"
cursor = "#2f81f7"
selection_bg = "#3b5070"
selection_fg = "#ffffff"
black = "#484f58"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"
bright_black = "#6e7681"
bright_red = "#ffa198"
bright_green = "#56d364"
bright_yellow = "#e3b341"
bright_blue = "#79c0ff"
bright_magenta = "#d2a8ff"
bright_cyan = "#56d4dd"
bright_white = "#ffffff"
